version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
     - 22181:2181

  broker:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
     - zookeeper
     - broker
    ports:
     - 8083:8080
    environment:
     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
     KAFKA_CLUSTERS_0_ZOOKEEPERS: zookeeper:2181
  dynamic-kafka:
    image: openjdk:11-jre-slim-buster
    depends_on:
     - kafka-ui
    ports:
     - 8081:8081
    volumes:
     - /home/hainv/Documents/apachestorm/code/Dynamic-Kafka-Consumer/target/:/jarfile/
    command: ["java", "-jar", "/jarfile/dynamic-kafka-consumer-1.0.0-1-SNAPSHOT.jar"]
  dynamic-kafka1:
    image: openjdk:11-jre-slim-buster
    depends_on:
     - kafka-ui
    ports:
     - 8082:8081
    volumes:
     - /home/hainv/Documents/apachestorm/code/Dynamic-Kafka-Consumer/target/:/jarfile/
    command: ["java", "-jar", "/jarfile/dynamic-kafka-consumer-1.0.0-1-SNAPSHOT.jar"]